#version: '3.8'
services:
  # O Coração: Kafka em modo KRaft (mais leve e moderno)
  kafka:
      image: confluentinc/cp-kafka:7.5.0
      container_name: security-kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
        KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        CLUSTER_ID: 'MkU3ODA4NGU3N2I0M2VjYQ=='
      healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "9092"] # Testa apenas se a porta está aberta
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s # IMPORTANTE: Dá 30 segundos de "folga" antes de começar a cobrar saúde
  # A Visão: Kafdrop (Interface para o seu canal do YouTube ver as mensagens)
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: security-kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      kafka:
        condition: service_healthy
  # O Cofre: PostgreSQL para os logs de auditoria
  db-audit:
    image: postgres:15
    container_name: security-db
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_password
      POSTGRES_DB: security_audit_db
    ports:
      - "5432:5432"