
# Desativa a criação automática de containers pelo Quarkus
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

# Configurações do Banco de Dados (apontando para o seu Docker Compose)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sentinel
quarkus.datasource.password=sentinel_password
quarkus.datasource.reactive.url=postgresql://localhost:5432/security_audit_db

# Como ainda não temos entidades @Entity, vamos silenciar o Hibernate por enquanto
quarkus.hibernate-orm.database.generation=none


# Configurações do Kafka Outgoing (Saída)
mp.messaging.outgoing.security-audit.connector=smallrye-kafka
mp.messaging.outgoing.security-audit.topic=security-audit-topic
mp.messaging.outgoing.security-audit.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Kafka Broker (Externo no Docker)
kafka.bootstrap.servers=localhost:9092

