
# Configurações do Banco de Dados (apontando para o seu Docker Compose)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sentinel
quarkus.datasource.password=sentinel_password
quarkus.datasource.reactive.url=postgresql://127.0.0.1:5432/security_audit_db

# Como ainda não temos entidades @Entity, vamos silenciar o Hibernate por enquanto
quarkus.hibernate-orm.database.generation=none

quarkus.log.category."io.smallrye.reactive.messaging.kafka".level=DEBUG

# Quarkus Dev Services - Desativados para usar o seu Docker
quarkus.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

# Endereço do Broker (Alinhado com o Docker)
kafka.bootstrap.servers=kafka:9092

# --- PRODUCER (Caminho de Saída) ---
mp.messaging.outgoing.security-audit-out.connector=smallrye-kafka
mp.messaging.outgoing.security-audit-out.topic=security-audit-topic
mp.messaging.outgoing.security-audit-out.value.serializer=br.com.venhaserjava.model.SecurityEventSerializer

# --- CONSUMER (Entrada) ---
mp.messaging.incoming.security-audit-in.connector=smallrye-kafka
mp.messaging.incoming.security-audit-in.topic=security-audit-topic
mp.messaging.incoming.security-audit-in.group.id=security-sentinel-v4

mp.messaging.incoming.security-audit-in.value.deserializer=br.com.venhaserjava.model.SecurityEventDeserializer
mp.messaging.incoming.security-audit-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.incoming.security-audit-in.payload-type=br.com.venhaserjava.model.SecurityEvent

mp.messaging.incoming.security-audit-in.auto.offset.reset=earliest

# Aumenta o tempo de espera para o join do grupo (útil em ambientes Docker/Ubuntu)
mp.messaging.incoming.security-audit-in.metadata.max.age.ms=30000
mp.messaging.incoming.security-audit-in.session.timeout.ms=45000

# Deserializers para converter JSON de volta para Objeto Java

# --- CONFIGURAÇÃO DE DLQ ---
mp.messaging.incoming.security-audit-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.security-audit-in.dead-letter-queue.topic=security-audit-dead-letter
mp.messaging.incoming.security-audit-in.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.security-audit-in.dead-letter-queue.value.serializer=br.com.venhaserjava.model.SecurityEventSerializer

# quarkus.kafka.deserializer.jackson.br.com.venhaserjava.model.SecurityEvent=br.com.venhaserjava.model.SecurityEvent

# Força o Quarkus a reportar o estado do Kafka no Health Check
quarkus.smallrye-health.enabled=true

quarkus.log.level=INFO
quarkus.log.category."io.smallrye.reactive.messaging".level=DEBUG

