
# Desativa a criação automática de containers pelo Quarkus
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

# Configurações do Banco de Dados (apontando para o seu Docker Compose)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=sentinel
quarkus.datasource.password=sentinel_password
quarkus.datasource.reactive.url=postgresql://localhost:5432/security_audit_db

# Como ainda não temos entidades @Entity, vamos silenciar o Hibernate por enquanto
quarkus.hibernate-orm.database.generation=none

# # Configurações do Kafka Outgoing (Saída)
# mp.messaging.outgoing.security-audit.connector=smallrye-kafka
# mp.messaging.outgoing.security-audit.topic=security-audit-topic
# mp.messaging.outgoing.security-audit.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# # Configuração do Consumidor (Incoming)
# mp.messaging.incoming.security-audit.connector=smallrye-kafka
# mp.messaging.incoming.security-audit.topic=security-audit-topic
# mp.messaging.incoming.security-audit.auto.offset.reset=earliest

# # Estratégia de DLQ
# mp.messaging.incoming.security-audit.failure-strategy=dead-letter-queue
# mp.messaging.incoming.security-audit.dead-letter-queue.topic=security-audit-dead-letter

# Configurações do Kafka Outgoing (Saída - Canal renomeado para security-audit-out)
mp.messaging.outgoing.security-audit-out.connector=smallrye-kafka
mp.messaging.outgoing.security-audit-out.topic=security-audit-topic
mp.messaging.outgoing.security-audit-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Configuração do Consumidor (Incoming - Canal renomeado para security-audit-in)
mp.messaging.incoming.security-audit-in.connector=smallrye-kafka
mp.messaging.incoming.security-audit-in.topic=security-audit-topic
mp.messaging.incoming.security-audit-in.auto.offset.reset=earliest

# Estratégia de DLQ (Ajuste o prefixo para coincidir com o novo nome do canal de entrada)
mp.messaging.incoming.security-audit-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.security-audit-in.dead-letter-queue.topic=security-audit-dead-letter

# Kafka Broker (Externo no Docker)
kafka.bootstrap.servers=localhost:9092

